import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';
import type { CohortResult, PersonalizedResult } from '@shared/schema';

interface BrandingConfig {
  orgName: string;
  orgLogo?: string;
  primaryColor?: string; // Hex color
}

/**
 * Convert hex color to RGB values for jsPDF
 */
function hexToRgb(hex: string): [number, number, number] {
  const result = /^#?([a-f\d]{2})([a-f\d]{2})([a-f\d]{2})$/i.exec(hex);
  return result
    ? [parseInt(result[1], 16), parseInt(result[2], 16), parseInt(result[3], 16)]
    : [139, 92, 246]; // Default purple
}

/**
 * Add branded header to PDF
 */
async function addBrandedHeader(
  doc: jsPDF,
  branding: BrandingConfig,
  title: string
) {
  const pageWidth = doc.internal.pageSize.getWidth();
  const primaryRgb = branding.primaryColor
    ? hexToRgb(branding.primaryColor)
    : [139, 92, 246];

  // Add logo if available
  if (branding.orgLogo) {
    try {
      // Fetch and convert logo to base64 if it's a URL
      let logoData = branding.orgLogo;
      if (branding.orgLogo.startsWith('http')) {
        const response = await fetch(branding.orgLogo);
        const blob = await response.blob();
        logoData = await new Promise<string>((resolve) => {
          const reader = new FileReader();
          reader.onloadend = () => resolve(reader.result as string);
          reader.readAsDataURL(blob);
        });
      }
      doc.addImage(logoData, 'PNG', 15, 15, 30, 15);
    } catch (error) {
      console.error('Failed to load logo:', error);
      // Continue without logo
    }
  }

  // Add organization name
  doc.setFontSize(10);
  doc.setTextColor(100, 100, 100);
  doc.text(branding.orgName, branding.orgLogo ? 50 : 15, 20);

  // Add Nebula branding
  doc.setFontSize(12);
  doc.setTextColor(primaryRgb[0], primaryRgb[1], primaryRgb[2]);
  doc.text('Nebula', branding.orgLogo ? 50 : 15, 27);

  // Add title
  doc.setFontSize(20);
  doc.setTextColor(0, 0, 0);
  doc.text(title, 15, 45);

  // Add horizontal line
  doc.setDrawColor(primaryRgb[0], primaryRgb[1], primaryRgb[2]);
  doc.setLineWidth(0.5);
  doc.line(15, 50, pageWidth - 15, 50);

  return 55; // Return Y position for content to start
}

/**
 * Add footer to PDF
 */
function addFooter(doc: jsPDF, branding: BrandingConfig) {
  const pageHeight = doc.internal.pageSize.getHeight();
  const pageWidth = doc.internal.pageSize.getWidth();

  doc.setFontSize(8);
  doc.setTextColor(150, 150, 150);
  doc.text(
    `Generated by Nebula | ${branding.orgName} | ${new Date().toLocaleDateString()}`,
    pageWidth / 2,
    pageHeight - 10,
    { align: 'center' }
  );
}

/**
 * Generate branded PDF for cohort results
 */
export async function generateCohortResultsPDF(
  cohortResult: CohortResult,
  branding: BrandingConfig,
  workspaceName: string
): Promise<void> {
  const doc = new jsPDF();
  const primaryRgb = branding.primaryColor
    ? hexToRgb(branding.primaryColor)
    : [139, 92, 246];

  // Add header
  let yPos = await addBrandedHeader(doc, branding, 'Cohort Results');

  // Add workspace info
  doc.setFontSize(12);
  doc.setTextColor(100, 100, 100);
  doc.text(`Workspace: ${workspaceName}`, 15, yPos + 5);
  yPos += 15;

  // Add summary section
  doc.setFontSize(14);
  doc.setTextColor(primaryRgb[0], primaryRgb[1], primaryRgb[2]);
  doc.text('Executive Summary', 15, yPos);
  yPos += 8;

  doc.setFontSize(10);
  doc.setTextColor(0, 0, 0);
  const summaryLines = doc.splitTextToSize(
    cohortResult.summary || '',
    doc.internal.pageSize.getWidth() - 30
  );
  doc.text(summaryLines, 15, yPos);
  yPos += summaryLines.length * 5 + 10;

  // Add key themes
  const keyThemes = cohortResult.keyThemes as string[] | undefined;
  if (keyThemes && keyThemes.length > 0) {
    if (yPos > 240) {
      doc.addPage();
      yPos = 20;
    }

    doc.setFontSize(14);
    doc.setTextColor(primaryRgb[0], primaryRgb[1], primaryRgb[2]);
    doc.text('Key Themes', 15, yPos);
    yPos += 8;

    doc.setFontSize(10);
    doc.setTextColor(0, 0, 0);
    keyThemes.forEach((theme) => {
      if (yPos > 270) {
        doc.addPage();
        yPos = 20;
      }
      doc.text(`• ${theme}`, 20, yPos);
      yPos += 6;
    });
    yPos += 5;
  }

  // Add top ideas table
  const topIdeas = cohortResult.topIdeas as Array<{
    rank?: number;
    overallRank?: number;
    content: string;
    category?: string;
    pairwiseWins?: number;
    bordaScore?: number;
    marketplaceCoins?: number;
  }> | undefined;
  
  if (topIdeas && topIdeas.length > 0) {
    if (yPos > 200) {
      doc.addPage();
      yPos = 20;
    }

    doc.setFontSize(14);
    doc.setTextColor(primaryRgb[0], primaryRgb[1], primaryRgb[2]);
    doc.text('Top Ideas', 15, yPos);
    yPos += 5;

    const tableData = topIdeas.slice(0, 10).map((idea) => [
      String(idea.rank || idea.overallRank || '-'),
      idea.content,
      idea.category || 'Uncategorized',
      String(idea.pairwiseWins || 0),
      String(idea.bordaScore || 0),
      String(idea.marketplaceCoins || 0),
    ]);

    autoTable(doc, {
      startY: yPos,
      head: [['Rank', 'Idea', 'Category', 'Wins', 'Borda', 'Coins']],
      body: tableData,
      theme: 'striped',
      headStyles: {
        fillColor: [primaryRgb[0], primaryRgb[1], primaryRgb[2]],
        textColor: [255, 255, 255],
        fontSize: 9,
      },
      bodyStyles: {
        fontSize: 8,
      },
      columnStyles: {
        0: { cellWidth: 15 },
        1: { cellWidth: 70 },
        2: { cellWidth: 35 },
        3: { cellWidth: 15 },
        4: { cellWidth: 15 },
        5: { cellWidth: 15 },
      },
    });

    yPos = (doc as any).lastAutoTable.finalY + 10;
  }

  // Add insights
  if (cohortResult.insights) {
    if (yPos > 200) {
      doc.addPage();
      yPos = 20;
    }

    doc.setFontSize(14);
    doc.setTextColor(primaryRgb[0], primaryRgb[1], primaryRgb[2]);
    doc.text('Key Insights', 15, yPos);
    yPos += 8;

    doc.setFontSize(10);
    doc.setTextColor(0, 0, 0);
    const insightLines = doc.splitTextToSize(
      cohortResult.insights,
      doc.internal.pageSize.getWidth() - 30
    );
    doc.text(insightLines, 15, yPos);
    yPos += insightLines.length * 5 + 10;
  }

  // Add recommendations
  if (cohortResult.recommendations) {
    if (yPos > 240) {
      doc.addPage();
      yPos = 20;
    }

    doc.setFontSize(14);
    doc.setTextColor(primaryRgb[0], primaryRgb[1], primaryRgb[2]);
    doc.text('Recommendations', 15, yPos);
    yPos += 8;

    doc.setFontSize(10);
    doc.setTextColor(0, 0, 0);
    const recLines = doc.splitTextToSize(
      cohortResult.recommendations,
      doc.internal.pageSize.getWidth() - 30
    );
    doc.text(recLines, 15, yPos);
  }

  // Add footer
  addFooter(doc, branding);

  // Download PDF
  const fileName = `${workspaceName.replace(/[^a-z0-9]/gi, '_')}_Cohort_Results_${new Date().toISOString().split('T')[0]}.pdf`;
  doc.save(fileName);
}

/**
 * Generate branded PDF for personalized results
 */
export async function generatePersonalizedResultsPDF(
  personalizedResult: PersonalizedResult,
  branding: BrandingConfig,
  participantName: string,
  workspaceName: string
): Promise<void> {
  const doc = new jsPDF();
  const primaryRgb = branding.primaryColor
    ? hexToRgb(branding.primaryColor)
    : [139, 92, 246];

  // Add header
  let yPos = await addBrandedHeader(doc, branding, 'Personalized Results');

  // Add participant info
  doc.setFontSize(12);
  doc.setTextColor(100, 100, 100);
  doc.text(`Participant: ${participantName}`, 15, yPos + 5);
  doc.text(`Workspace: ${workspaceName}`, 15, yPos + 10);
  yPos += 20;

  // Add alignment score
  if (personalizedResult.alignmentScore !== null) {
    doc.setFontSize(14);
    doc.setTextColor(primaryRgb[0], primaryRgb[1], primaryRgb[2]);
    doc.text('Cohort Alignment Score', 15, yPos);
    yPos += 8;

    doc.setFontSize(24);
    doc.setTextColor(primaryRgb[0], primaryRgb[1], primaryRgb[2]);
    doc.text(`${personalizedResult.alignmentScore}%`, 15, yPos);
    yPos += 15;
  }

  // Add personal summary
  doc.setFontSize(14);
  doc.setTextColor(primaryRgb[0], primaryRgb[1], primaryRgb[2]);
  doc.text('Your Journey', 15, yPos);
  yPos += 8;

  doc.setFontSize(10);
  doc.setTextColor(0, 0, 0);
  const summaryLines = doc.splitTextToSize(
    personalizedResult.personalSummary || '',
    doc.internal.pageSize.getWidth() - 30
  );
  doc.text(summaryLines, 15, yPos);
  yPos += summaryLines.length * 5 + 10;

  // Add top contributions
  const topContributions = personalizedResult.topContributions as Array<{
    noteId: string;
    content: string;
    impact: string;
  }> | undefined;
  
  if (topContributions && topContributions.length > 0) {
    if (yPos > 200) {
      doc.addPage();
      yPos = 20;
    }

    doc.setFontSize(14);
    doc.setTextColor(primaryRgb[0], primaryRgb[1], primaryRgb[2]);
    doc.text('Your Top Contributions', 15, yPos);
    yPos += 8;

    topContributions.forEach((contribution, index) => {
      if (yPos > 250) {
        doc.addPage();
        yPos = 20;
      }

      doc.setFontSize(10);
      doc.setTextColor(primaryRgb[0], primaryRgb[1], primaryRgb[2]);
      doc.text(`#${index + 1}`, 15, yPos);

      doc.setTextColor(0, 0, 0);
      const contentLines = doc.splitTextToSize(contribution.content, 160);
      doc.text(contentLines, 25, yPos);
      yPos += contentLines.length * 5 + 2;

      doc.setTextColor(100, 100, 100);
      const impactLines = doc.splitTextToSize(contribution.impact, 160);
      doc.text(impactLines, 25, yPos);
      yPos += impactLines.length * 5 + 8;
    });
  }

  // Add insights
  if (personalizedResult.insights) {
    if (yPos > 200) {
      doc.addPage();
      yPos = 20;
    }

    doc.setFontSize(14);
    doc.setTextColor(primaryRgb[0], primaryRgb[1], primaryRgb[2]);
    doc.text('Personalized Insights', 15, yPos);
    yPos += 8;

    doc.setFontSize(10);
    doc.setTextColor(0, 0, 0);
    const insightLines = doc.splitTextToSize(
      personalizedResult.insights,
      doc.internal.pageSize.getWidth() - 30
    );
    doc.text(insightLines, 15, yPos);
    yPos += insightLines.length * 5 + 10;
  }

  // Add recommendations
  if (personalizedResult.recommendations) {
    if (yPos > 240) {
      doc.addPage();
      yPos = 20;
    }

    doc.setFontSize(14);
    doc.setTextColor(primaryRgb[0], primaryRgb[1], primaryRgb[2]);
    doc.text('Next Steps & Recommendations', 15, yPos);
    yPos += 8;

    doc.setFontSize(10);
    doc.setTextColor(0, 0, 0);
    const recLines = doc.splitTextToSize(
      personalizedResult.recommendations,
      doc.internal.pageSize.getWidth() - 30
    );
    doc.text(recLines, 15, yPos);
  }

  // Add footer
  addFooter(doc, branding);

  // Download PDF
  const fileName = `${participantName.replace(/[^a-z0-9]/gi, '_')}_Personalized_Results_${new Date().toISOString().split('T')[0]}.pdf`;
  doc.save(fileName);
}
