/**
 * Export the Reveille Software "May 2026 Offsite" workshop data to a JSON file.
 *
 * NOTE: The export file `reveille-workshop-export.json` was already generated
 * on 2026-05-22 via the Replit code_execution tool (which connects directly to
 * the production database). The export contains 338 rows across all tables,
 * verified with proper JSONB encoding.
 *
 * To re-run this script against the production database, set DATABASE_URL to
 * the production connection string before running:
 *
 *   DATABASE_URL=<prod_url> npx tsx scripts/export-reveille-workshop.ts
 *
 * Output: scripts/reveille-workshop-export.json
 */

import { writeFileSync } from "fs";
import { join, dirname } from "path";
import { fileURLToPath } from "url";
import { neon } from "@neondatabase/serverless";

const __dirname = dirname(fileURLToPath(import.meta.url));

if (!process.env.DATABASE_URL) {
  console.error("DATABASE_URL is not set. Set it to the production connection string.");
  process.exit(1);
}

const sql = neon(process.env.DATABASE_URL);

const ORG_ID = "ed533544-1c8f-482a-9b58-615c3d0357c8";
const PROJECT_ID = "dba06206-21cf-4ac8-a201-44a4acdeee9a";
const SPACE_IDS = [
  "1a01e989-b3f1-4044-941f-e560cd805d43", // MSP Use Cases
  "ec67edad-d9ea-4749-98d0-738f865ae0c8", // GTM Use Cases
  "78342ce3-04d3-4201-82f5-448738f5cbeb", // Customer Use Cases
];

// Uses json_agg(row_to_json(t)) so JSONB columns (config, top_ideas, etc.) are
// returned as proper nested objects — not the mangled CSV representation.
async function qj(query: string): Promise<unknown[]> {
  const wrapped = `SELECT json_agg(row_to_json(t)) FROM (${query}) t`;
  const rows = await sql(wrapped) as any[];
  return rows?.[0]?.json_agg ?? [];
}

async function main() {
  console.log("Exporting Reveille Software / May 2026 Offsite workshop data…");
  const inList = SPACE_IDS.map((id) => `'${id}'`).join(",");

  const [
    organizations, projects, projectMembers, companyAdmins,
    spaces, spaceFacilitators, participants, categories,
    notes, votes, rankings, marketplaceAllocations,
    workspaceModules, workspaceModuleRuns,
    priorityMatrices, staircaseModules,
    surveyQuestions, surveyResponses,
    cohortResults, personalizedResults,
    kbDocuments, ideas,
  ] = await Promise.all([
    qj(`SELECT * FROM organizations WHERE id = '${ORG_ID}'`),
    qj(`SELECT * FROM projects WHERE id = '${PROJECT_ID}'`),
    qj(`SELECT * FROM project_members WHERE project_id = '${PROJECT_ID}'`),
    qj(`SELECT * FROM company_admins WHERE organization_id = '${ORG_ID}'`),
    qj(`SELECT * FROM spaces WHERE id IN (${inList})`),
    qj(`SELECT * FROM space_facilitators WHERE space_id IN (${inList})`),
    qj(`SELECT * FROM participants WHERE space_id IN (${inList})`),
    qj(`SELECT * FROM categories WHERE space_id IN (${inList})`),
    qj(`SELECT * FROM notes WHERE space_id IN (${inList})`),
    qj(`SELECT * FROM votes WHERE space_id IN (${inList})`),
    qj(`SELECT * FROM rankings WHERE space_id IN (${inList})`),
    qj(`SELECT * FROM marketplace_allocations WHERE space_id IN (${inList})`),
    qj(`SELECT * FROM workspace_modules WHERE space_id IN (${inList})`),
    qj(`SELECT * FROM workspace_module_runs WHERE space_id IN (${inList})`),
    qj(`SELECT * FROM priority_matrices WHERE space_id IN (${inList})`),
    qj(`SELECT * FROM staircase_modules WHERE space_id IN (${inList})`),
    qj(`SELECT * FROM survey_questions WHERE space_id IN (${inList})`),
    qj(`SELECT * FROM survey_responses WHERE space_id IN (${inList})`),
    qj(`SELECT * FROM cohort_results WHERE space_id IN (${inList})`),
    qj(`SELECT * FROM personalized_results WHERE space_id IN (${inList})`),
    qj(`SELECT * FROM knowledge_base_documents WHERE space_id IN (${inList})`),
    qj(`SELECT * FROM ideas WHERE space_id IN (${inList})`),
  ]);

  const matrixIds  = (priorityMatrices  as any[]).map((m: any) => `'${m.id}'`).join(",");
  const staircaseIds = (staircaseModules as any[]).map((m: any) => `'${m.id}'`).join(",");
  const ideaIds    = (ideas             as any[]).map((i: any) => `'${i.id}'`).join(",");
  const kbDocIds   = (kbDocuments       as any[]).map((d: any) => `'${d.id}'`).join(",");

  const [priorityMatrixPositions, staircasePositions, ideaContributions, kbChunks] =
    await Promise.all([
      matrixIds    ? qj(`SELECT * FROM priority_matrix_positions WHERE matrix_id IN (${matrixIds})`) : [],
      staircaseIds ? qj(`SELECT * FROM staircase_positions WHERE staircase_id IN (${staircaseIds})`) : [],
      ideaIds      ? qj(`SELECT * FROM idea_contributions WHERE idea_id IN (${ideaIds})`) : [],
      // Exclude search_vector tsvector — regenerated by backfill-kb-chunks.ts after import
      kbDocIds     ? qj(`SELECT id, document_id, chunk_index, content, created_at FROM knowledge_base_chunks WHERE document_id IN (${kbDocIds})`) : [],
    ]);

  const exportPayload = {
    exportedAt: new Date().toISOString(),
    exportVersion: 2,
    note: "Reveille Software / May 2026 Offsite — 3 workspaces created 2026-05-21",
    orgId: ORG_ID,
    projectId: PROJECT_ID,
    spaceIds: SPACE_IDS,
    tables: {
      organizations, projects, projectMembers, companyAdmins,
      spaces, spaceFacilitators, participants, categories,
      notes, votes, rankings, marketplaceAllocations,
      workspaceModules, workspaceModuleRuns,
      priorityMatrices, priorityMatrixPositions,
      staircaseModules, staircasePositions,
      surveyQuestions, surveyResponses,
      cohortResults, personalizedResults,
      kbDocuments, kbChunks,
      ideas, ideaContributions,
    },
  };

  const outPath = join(__dirname, "reveille-workshop-export.json");
  writeFileSync(outPath, JSON.stringify(exportPayload, null, 2));

  let total = 0;
  console.log("\nExport summary:");
  for (const [table, rows] of Object.entries(exportPayload.tables)) {
    const n = (rows as any[]).length;
    if (n > 0) { console.log(`  ${table.padEnd(28)} ${n} rows`); total += n; }
  }
  console.log(`\n  Total rows: ${total}`);
  console.log(`  Saved to: ${outPath}`);
  console.log("\nNEXT STEPS:");
  console.log("  1. Restore the database snapshot");
  console.log("  2. npx tsx scripts/import-reveille-workshop.ts");
  console.log("  3. npx tsx scripts/backfill-kb-chunks.ts");
}

main()
  .then(() => process.exit(0))
  .catch((err) => { console.error("Export failed:", err); process.exit(1); });
